In [75]:
import pandas as pd
import json
import matplotlib.pyplot as plt

In [136]:
results = pd.concat([pd.read_json('results/result_2.json'), pd.read_json('results/result_1.json')])

In [142]:
print(results.shape)
results.head()

(3645, 7)

,filename,annotation_count,weight,threshold,true_positive,false_positive,false_negative
0,212,2748,0.2,0.7,2746,6219,2
1,212,2748,0.2,0.8,2743,6251,5
2,212,2748,0.2,0.9,2747,6260,1
3,212,2748,0.3,0.7,2746,6220,2
4,212,2748,0.3,0.8,2743,6251,5

In [135]:
results_per_param = results.drop(columns=['filename']).groupby(['weight', 'threshold'])
results_per_param = results_per_param.sum().reset_index()
results_per_param['accuracy'] = results_per_param['true_positive']  / (results_per_param['true_positive'] + results_per_param['false_negative'] + results_per_param['false_positive']) 
results_per_param['precision'] = results_per_param['true_positive']  / (results_per_param['true_positive'] + results_per_param['false_positive'])
results_per_param['recall'] = results_per_param['true_positive']  / (results_per_param['true_positive'] + results_per_param['false_negative']) 
results_per_param['TP detection %'] = results_per_param['true_positive']  / results_per_param['annotation_count']

weight_best_acc, threshold_best_acc, best_acc = results_per_param.sort_values('accuracy', ascending=False).iloc[0][['weight', 'threshold', 'accuracy']]

print(f'Best acc for weight: {weight_best_acc}, threshold: {threshold_best_acc} -> {best_acc}')

Best acc for weight: 0.2, threshold: 0.2 -> 0.33227644227732656

## Accuracy dla wszystkich ta≈õm dla (weight, threshold)

In [109]:
table_1 = pd.pivot_table(results_per_param, values='accuracy', index=['weight'], columns=['threshold'])
table_1

threshold,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9
weight,,,,,,,,,
0.20,0.294132,0.332276,0.302154,0.279060,0.264950,0.254455,0.244683,0.234665,0.226024
0.30,0.293608,0.331925,0.301931,0.278924,0.264848,0.254383,0.244602,0.234594,0.225965
0.40,0.293241,0.331656,0.301843,0.278843,0.264772,0.254342,0.244555,0.234568,0.225931
0.50,0.293055,0.331537,0.301772,0.278788,0.264746,0.254301,0.244530,0.234544,0.225921
0.60,0.292860,0.331478,0.301735,0.278769,0.264722,0.254281,0.244515,0.234533,0.225911
0.70,0.292783,0.331406,0.301695,0.278747,0.264702,0.254268,0.244510,0.234529,0.225902
0.80,0.292740,0.331362,0.301672,0.278730,0.264690,0.254266,0.244506,0.234522,0.225897
0.90,0.292691,0.331325,0.301659,0.278730,0.264687,0.254259,0.244501,0.234515,0.225896
0.95,0.292636,0.331314,0.301653,0.278728,0.264685,0.254256,0.244500,0.234515,0.225893

In [123]:
results['accuracy'] = results['true_positive']  / (results['true_positive'] + results['false_negative'] + results['false_positive']) 
results['precision'] = results['true_positive']  / (results['true_positive'] + results['false_positive'])
results['recall'] = results['true_positive']  / (results['true_positive'] + results['false_negative']) 
results['TP detection %'] = results['true_positive']  / results['annotation_count']

## Najlepsze accuracy dla ta≈õm

In [122]:
results.groupby(['filename']).max().reset_index()[['filename', 'accuracy']]

    filename  accuracy
0        100  0.625581
1        101  0.509102
2        102  0.745353
3        103  0.270722
4        104  0.253102
5        105  0.482259
6        106  0.220932
7        107  0.315798
8        108  0.283853
9        112  0.250974
10       113  0.240678
11       114  0.199926
12       115  0.542947
13       116  0.726027
14       117  0.131474
15       118  0.915275
16       119  0.593524
17       121  0.502650
18       122  0.999193
19       123  0.923780
20       124  0.825649
21       200  0.266773
22       201  0.406476
23       202  0.516320
24       203  0.393128
25       205  0.672559
26       207  0.045930
27       208  0.261517
28       209  0.359758
29       210  0.539200
30       212  0.321661
31       213  0.344229
32       215  0.357127
33       217  0.275196
34       219  0.643194
35       220  0.636045
36       221  0.445100
37       222  0.325109
38       223  0.704990
39       228  0.255656
40       230  0.342645
41       231  0.177070
42       232  0.337926
43       233  0.333172
44       234  0.417105

## ca≈Çkowite accuracy

In [115]:
results

,filename,annotation_count,weight,threshold,true_positive,false_positive,false_negative,accuracy,precision,recall
0,212,2748,0.20,0.7,2746,6219,2,0.306234,0.306302,0.999272
1,212,2748,0.20,0.8,2743,6251,5,0.304812,0.304981,0.998180
2,212,2748,0.20,0.9,2747,6260,1,0.304951,0.304985,0.999636
3,212,2748,0.30,0.7,2746,6220,2,0.306200,0.306268,0.999272
4,212,2748,0.30,0.8,2743,6251,5,0.304812,0.304981,0.998180
...,...,...,...,...,...,...,...,...,...,...
2425,116,2303,0.95,0.2,1654,848,649,0.524913,0.661071,0.718194
2426,116,2303,0.95,0.3,2048,607,255,0.703780,0.771375,0.889275
2427,116,2303,0.95,0.4,2226,770,77,0.724374,0.742991,0.966565
2428,116,2303,0.95,0.5,2258,1199,45,0.644774,0.653167,0.980460
2429,116,2303,0.95,0.6,2257,1660,46,0.569518,0.576206,0.980026